OnlineBookStore/OnlineBookStore/Models/BookCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineBookStore.Models
{
    public class BookCategory
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BookCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public List<Book> Books { get; set; }
    }
}

OnlineBookStore/OnlineBookStore/Controllers/BookCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineBookStore.Models;

namespace OnlineBookStore.Controllers
{
    public class BookCategoryController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            HttpResponseMessage response = client.GetAsync("/api/bookcategory").Result;
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<BookCategory> data = JsonConvert.DeserializeObject<List<BookCategory>>(stringData);

            return View(data);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(BookCategory bookCategory)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");

            string stringData = JsonConvert.SerializeObject(bookCategory);
            var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/bookcategory", contentData).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/bookcategory/" + id).Result;


            string stringData = response.Content.ReadAsStringAsync().Result;

            BookCategory data = JsonConvert.DeserializeObject<BookCategory>(stringData);


            return View(data);
        }


        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/bookcategory/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            BookCategory data = JsonConvert.DeserializeObject<BookCategory>(stringData);

            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(BookCategory bookCategory)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            string stringData = JsonConvert.SerializeObject(bookCategory);

            var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PutAsync("/api/bookcategory/" + bookCategory.BookCategoryId, contentData).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/bookcategory/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            BookCategory data = JsonConvert.DeserializeObject<BookCategory>(stringData);

            return View(data);
        }

        [HttpPost]
        public ActionResult Delete(int id, BookCategory bookCategory)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            string stringData = JsonConvert.SerializeObject(bookCategory);



            //var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.DeleteAsync("/api/bookcategory/" + id).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");

        }

    }
}

OnlineBookStore/OnlineBookStore/Views/BookCategory/Create.cshtml
@model OnlineBookStore.Models.BookCategory

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*<h2>Create</h2>

<h4>BookCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookCategoryId" class="control-label"></label>
                <input asp-for="BookCategoryId" class="form-control" />
                <span asp-validation-for="BookCategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryDescription" class="control-label"></label>
                <input asp-for="CategoryDescription" class="form-control" />
                <span asp-validation-for="CategoryDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>*@

<br />
<br />
<br />

<h2><center><b><u>Add Book Category</u></b></center></h2>
<br />

@*<form asp-action="Create" asp-controller="BookCategory">



        <label asp-for="CategoryName"></label>
        <input type="text" asp-for="CategoryName" />
        <br />

        <label asp-for="CategoryDescription"></label>
        <input type="text" asp-for="CategoryDescription" />
        <br />


        <input type="submit" value="Save" class="btn btn-primary" />

    </form>*@

<form asp-action="Create" asp-controller="BookCategory">

    <div class="form-group">
        <label asp-for="CategoryName"><b>Category Name</b></label>
        <input type="text" asp-for="CategoryName" class="form-control" placeholder="Enter Category Name">
    </div>

    <div class="form-group">
        <label asp-for="CategoryDescription"><b>Category Description</b></label>
        <input type="text" asp-for="CategoryDescription" class="form-control" placeholder="Enter Category Description">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-controller="BookCategory" asp-action="Index" class="btn btn-primary">Back To List</a>
</form>

OnlineBookStore/OnlineBookStore/Views/BookCategory/Delete.cshtml
@model OnlineBookStore.Models.BookCategory
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<br />
<h2>Are you sure, you want to delete it?</h2>
<br />
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="~/images/logo.png" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><b>Category Id : </b>@Html.DisplayFor(model => model.BookCategoryId)</h5>

                <p class="card-text">  <b> Category Name : </b> @Html.DisplayFor(model => model.CategoryName)</p>
                <p class="card-text"><b> Category Description : </b> @Html.DisplayFor(model => model.CategoryDescription)</p>


            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("Delete", "BookCategory", FormMethod.Post))
{
    <p>
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-controller="BookCategory" asp-action="Index" class="btn btn-primary">Back To List</a>
    </p>
}

OnlineBookStore/OnlineBookStore/Views/BookCategory/Details.cshtml
@model OnlineBookStore.Models.BookCategory
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<br />
<h2>Details</h2>
<br />
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="~/images/logo.png" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><b>Category Id : </b>@Html.DisplayFor(model => model.BookCategoryId)</h5>

                <p class="card-text">  <b> Category Name : </b> @Html.DisplayFor(model => model.CategoryName)</p>
                <p class="card-text"><b> Category Description : </b> @Html.DisplayFor(model => model.CategoryDescription)</p>


            </div>
        </div>
    </div>
</div>
<a asp-controller="BookCategory" asp-action="Index" class="btn btn-primary">Back To List</a>
  

OnlineBookStore/OnlineBookStore/Views/BookCategory/Edit.cshtml
@model OnlineBookStore.Models.BookCategory
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<br />
<h2><center><b><u>Edit Book Category</u></b></center></h2>
<br />
@*<form asp-action="Edit" asp-controller="BookCategory">


        <label asp-for="CategoryId"></label>
        <input type="text" asp-for="CategoryId" />
        <br />

        <label asp-for="CategoryName"></label>
        <input type="text" asp-for="CategoryName" />
        <br />

        <label asp-for="CategoryDescription"></label>
        <input type="text" asp-for="CategoryDescription" />
        <br />


        <input type="submit" value="Save" class="btn btn-primary" />

    </form>*@


<form asp-action="Edit" asp-controller="BookCategory">

    @Html.HiddenFor(x => Model.BookCategoryId)

    <div class="form-group">
        <label asp-for="CategoryName"><b>Category Name</b></label>
        <input type="text" asp-for="CategoryName" class="form-control" placeholder="Enter Category Name">
    </div>

    <div class="form-group">
        <label asp-for="CategoryDescription"><b>Category Description</b></label>
        <input type="text" asp-for="CategoryDescription" class="form-control" placeholder="Enter Category Description">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-controller="BookCategory" asp-action="Index" class="btn btn-primary">Back To List</a>
</form>

OnlineBookStore/OnlineBookStore/Views/BookCategory/Index.cshtml
@model IEnumerable<OnlineBookStore.Models.BookCategory>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<br />
<br />

<h2><center><b><u>List Of Book Categories</u></b></center></h2>
<br />

<a asp-action="Create" asp-controller="BookCategory" class="btn btn-success">Add Book Category</a>
<br />
<br />
<table class="table table-striped">


    <thead>
        <tr>
            <th><label for="CategoryId">Category Id</label></th>
            <th><label for="CategoryName">Category Name</label></th>
            <th><label for="Actions">Actions</label></th>


        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.BookCategoryId)</td>
                <td> @Html.DisplayFor(modelItem => item.CategoryName)</td>



                <td>

                    <a asp-controller="BookCategory" asp-action="Edit" asp-route-id="@item.BookCategoryId" class="btn btn-info">Edit</a> |
                    <a asp-controller="BookCategory" asp-action="Details" asp-route-id="@item.BookCategoryId" class="btn btn-primary">Details</a> |
                    <a asp-controller="BookCategory" asp-action="Delete" asp-route-id="@item.BookCategoryId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>