OnlineBookStore/OnlineBookStore/Models/AuthorBiography.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineBookStore.Models
{
    public class AuthorBiography
    {

        public int AuthorBiographyId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public string Nationality { get; set; }
        public int AuthorId { get; set; }
        public Author Author { get; set; }
    }
}

OnlineBookStore/OnlineBookStore/Controllers/AuthorBiographyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineBookStore.Models;

namespace OnlineBookStore.Controllers
{
    public class AuthorBiographyController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            HttpResponseMessage response = client.GetAsync("/api/authorbiography").Result;
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<AuthorBiography> data = JsonConvert.DeserializeObject<List<AuthorBiography>>(stringData);

            return View(data);
        }
        [HttpGet]
        public ActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Create(AuthorBiography author)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");

            string stringData = JsonConvert.SerializeObject(author);
            var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/authorbiography", contentData).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");
        }



        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/authorbiography/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            AuthorBiography data = JsonConvert.DeserializeObject<AuthorBiography>(stringData);
            return View(data);
        }

        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/authorbiography/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            AuthorBiography data = JsonConvert.DeserializeObject<AuthorBiography>(stringData);

            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(AuthorBiography authorBiography)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            string stringData = JsonConvert.SerializeObject(authorBiography);



            var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PutAsync("/api/authorbiography/" + authorBiography.AuthorBiographyId, contentData).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/authorbiography/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            AuthorBiography data = JsonConvert.DeserializeObject<AuthorBiography>(stringData);

            return View(data);
        }

        [HttpPost]
        public ActionResult Delete(int id, AuthorBiography authorBiography)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            string stringData = JsonConvert.SerializeObject(authorBiography);



            //var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.DeleteAsync("/api/authorbiography/" + id).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");

        }

    }
}

OnlineBookStore/OnlineBookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineBookStore.Models;

namespace OnlineBookStore.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            HttpResponseMessage response = client.GetAsync("/api/book").Result;
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<Book> data = JsonConvert.DeserializeObject<List<Book>>(stringData);

            return View(data);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Book book)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");

            string stringData = JsonConvert.SerializeObject(book);
            var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/book", contentData).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/book/" + id).Result;


            string stringData = response.Content.ReadAsStringAsync().Result;

            Book data = JsonConvert.DeserializeObject<Book>(stringData);


            return View(data);
        }

        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/book/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            Book data = JsonConvert.DeserializeObject<Book>(stringData);

            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(Book book)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            string stringData = JsonConvert.SerializeObject(book);



            var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PutAsync("/api/book/" + book.BookId, contentData).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            HttpResponseMessage response = client.GetAsync("/api/book/" + id).Result;

            string stringData = response.Content.ReadAsStringAsync().Result;
            Book data = JsonConvert.DeserializeObject<Book>(stringData);

            return View(data);
        }

        [HttpPost]
        public ActionResult Delete(int id, Book book)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:61725");
            string stringData = JsonConvert.SerializeObject(book);



            //var contentData = new StringContent(stringData, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.DeleteAsync("/api/book/" + id).Result;
            ViewBag.Message = response.Content.ReadAsStringAsync().Result;
            return RedirectToAction("Index");

        }

    }
}

OnlineBookStore/OnlineBookStore/Views/AuthorBiography/Create.cshtml
@model OnlineBookStore.Models.AuthorBiography

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<br />
<h2><center><b><u>Add Author Biography</u></b></center></h2>
<br />


<form asp-action="Create" asp-controller="AuthorBiography">
    @*<div class="form-group">
        <label for="AuthorId"><b>Author's Name</b></label>
        <select asp-for="Author" asp-items="ViewBag.authors"></select>
    </div>*@

    <div class="form-group">
        <label asp-for="DateOfBirth"><b>Author's Date Of Birth</b></label>
        <input type="text" asp-for="DateOfBirth" class="form-control" placeholder="Enter Author's  Date Of Birth">

    </div>

    <div class="form-group">
        <label asp-for="BirthPlace"><b>Author's Birth Place</b></label>
        <input type="text" asp-for="BirthPlace" class="form-control" placeholder="Enter Author's  Birth Place">
    </div>

    <div class="form-group">
        <label asp-for="Nationality"><b>Author's Nationality</b></label>
        <input type="text" asp-for="Nationality" class="form-control" placeholder="Enter Author's  Nationality">
    </div>
    <input type="submit" value="Save" class="btn btn-success" />
    <a asp-controller="AuthorBiography" asp-action="Index" class="btn btn-primary">Back To List</a>

</form>

OnlineBookStore/OnlineBookStore/Views/AuthorBiography/Delete.cshtml
@model OnlineBookStore.Models.AuthorBiography
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<br />
<h2>Are you sure, you want to delete it?</h2>
<br />
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="~/images/logo.png" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><b>Date of Birth : </b>@Html.DisplayFor(model => model.AuthorId)</h5>
                <p class="card-text">  <b>Birth Place : </b> @Html.DisplayFor(model => model.BirthPlace)</p>
                <p class="card-text"><b> Nationality : </b> @Html.DisplayFor(model => model.Nationality)</p>
                <p class="card-text"><b> AuthorId : </b> @Html.DisplayFor(model => model.DateOfBirth)</p>


            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("Delete", "Book", FormMethod.Post))
{
    <p>
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-controller="AuthorBiography" asp-action="Index" class="btn btn-primary">Back To List</a>
    </p>
}

OnlineBookStore/OnlineBookStore/Views/AuthorBiography/Details.cshtml
@model OnlineBookStore.Models.AuthorBiography
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />
<br />
<h2>Details</h2>
<br />


<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="~/images/logo.png" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><b>Date of Birth : </b>@Html.DisplayFor(model => model.AuthorId)</h5>
                <p class="card-text">  <b>Birth Place : </b> @Html.DisplayFor(model => model.BirthPlace)</p>
                <p class="card-text"><b> Nationality : </b> @Html.DisplayFor(model => model.Nationality)</p>
                <p class="card-text"><b> AuthorId : </b> @Html.DisplayFor(model => model.DateOfBirth)</p>


            </div>
        </div>
    </div>
</div>

<a asp-controller="AuthorBiography" asp-action="Index" class="btn btn-primary">Back To List</a>

OnlineBookStore/OnlineBookStore/Views/AuthorBiography/Edit.cshtml
@model OnlineBookStore.Models.AuthorBiography
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<br />
<h2><center><b><u>Edit Author Biography</u></b></center></h2>
<br />
<form asp-action="Edit" asp-controller="AuthorBiography">

   
    @Html.HiddenFor(x => Model.AuthorBiographyId)

    <div class="form-group">
        <label asp-for="DateOfBirth"><b>Date Of Birth</b></label>
        <input type="text" asp-for="DateOfBirth" class="form-control" placeholder="Enter Author's  Date Of Birth">
    </div>

    <div class="form-group">
        <label asp-for="BirthPlace"><b>Birth Place</b></label>
        <input type="text" asp-for="BirthPlace" class="form-control" placeholder="Enter Author's  Birth Place">
    </div>

    <div class="form-group">
        <label asp-for="Nationality"><b>Nationality</b></label>
        <input type="text" asp-for="Nationality" class="form-control" placeholder="Enter Author's  Nationality">
    </div>

    <input type="submit" value="Save" class="btn btn-success" />
    <a asp-controller="AuthorBiography" asp-action="Index" class="btn btn-primary">Back To List</a>
</form>

OnlineBookStore/OnlineBookStore/Views/AuthorBiography/Index.cshtml
@model IEnumerable<OnlineBookStore.Models.AuthorBiography>
    @{
        ViewData["Title"] = "Index";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }

    <br />
    <br />
    <br />

    <h2><center><b><u>List Of Author Biographies</u></b></center></h2>
    <br />
    <a asp-action="Create" asp-controller="AuthorBiography" class="btn btn-success">Add Author Biography</a>
    <br />
    <br />
    <table class="table table-striped">

        <thead>
            <tr>
                <th><label for="AuthorBiograpghyId">Author's Biography Id</label></th>
                <th><label for="DateofBirth">Date of Birth</label></th>
                <th><label for="BirthPlace">Birth Place</label></th>
                <th><label for="Nationality">Nationality</label></th>
                <th><label for="Actions">Actions</label></th>


            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td> @Html.DisplayFor(modelItem => item.AuthorBiographyId)</td>
                    <td> @Html.DisplayFor(modelItem => item.DateOfBirth)</td>
                    <td> @Html.DisplayFor(modelItem => item.BirthPlace)</td>
                    <td> @Html.DisplayFor(modelItem => item.Nationality)</td>


                    <td>

                        <a asp-controller="AuthorBiography" asp-action="Edit" asp-route-id="@item.AuthorBiographyId" class="btn btn-info">Edit </a> |
                        <a asp-controller="AuthorBiography" asp-action="Details" asp-route-id="@item.AuthorBiographyId" class="btn btn-primary">Details </a> |
                        <a asp-controller="AuthorBiography" asp-action="Delete" asp-route-id="@item.AuthorBiographyId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />